#include <SDL2/SDL.h> // Simple Directmedia Layer lib has to be installed
#include <SDL2/SDL_image.h> // for loading PNG images
#include <memory>
#include <iostream>
#include <fstream>
#include "object.h"
using namespace std;


SDL_Renderer* ImageLoader::renderer;

// load an image as an SDL2 texture
SDL_Texture* ImageLoader::getImage(const string& filename){
    SDL_Surface* img = IMG_Load( filename.c_str() );
    // TODO: optimize surface: optimizedSurface = SDL_ConvertSurface( loadedSurface, gScreenSurface->format, 0 );
    if(!renderer){
        cout << "ERROR: SDL renderer was not set." << endl;
        return nullptr;
    }
    SDL_Texture* texture = SDL_CreateTextureFromSurface(renderer, img);
    SDL_FreeSurface(img);
    return texture;
}


const string OUTPUT_FILE_SCAD = "asm.scad";
const string TMP_FILE_SCAD = "tmp.scad";
const string TMP_FILE_IMG = "tmp.png";


bool makeObjectImage(shared_ptr<Object>& obj){
    // save openscad code from a module/operator to a temp file
    ofstream file(TMP_FILE_SCAD);
    if(!obj->saveScad(file)){
        cout << "Error saving openscad code to temp file " << TMP_FILE_SCAD << endl;
        return false;
    }
    file.close();

    // run openscad to produce TMP_FILE_IMG from TMP_FILE_SCAD
    string cmd = "openscad --viewall --autocenter -o "+TMP_FILE_IMG+" "+TMP_FILE_SCAD;
    cout << "Running " << cmd << endl;
    // TODO: run openscad

    // load the image generated by openscad and set it for the object
    SDL_Texture* texture = ImageLoader::getImage(TMP_FILE_IMG);
    if(!texture){ return false; }
    obj->setImage(texture);
    return true;
}


// returns a root object that gets rendered and renders all of its children
std::shared_ptr<Object> initGui(int width, int height){
    auto root   = make_shared<VerticalLayout>(width);
    auto menu   = make_shared<FlowLayout>(width);     // top menu
    auto level2 = make_shared<FlowLayout>(width);     // container for labels and main
    auto labels = make_shared<VerticalLayout>(2*ITEM_WIDTH); // module pics
    width = width-2*ITEM_WIDTH;
    auto main   = make_shared<VerticalLayout>(width); // main "code" area

    auto dzView       = make_shared<DropZoneView>();
    auto union_       = make_shared<Operator>(width, Operator::UNION);
    auto difference   = make_shared<Operator>(width, Operator::DIFFERENCE);
    auto intersection = make_shared<Operator>(width, Operator::INTERSECTION);
    auto translate    = make_shared<Modifier>(Modifier::TRANSLATE);
    auto rotate       = make_shared<Modifier>(Modifier::ROTATE);
    auto cube         = make_shared<Shape>(Shape::CUBE);
    auto cylinder     = make_shared<Shape>(Shape::CYLINDER);
    auto sphere       = make_shared<Shape>(Shape::SPHERE);
    auto dzDelete     = make_shared<DropZoneDelete>(); // TODO: pass labels and main in constructor

    root  ->add(menu);
    root  ->add(level2);
    level2->add(labels);
    level2->add(main);

    menu->add(dzView);
    menu->add(union_);
    menu->add(difference);
    menu->add(intersection);
    menu->add(translate);
    menu->add(rotate);
    menu->add(cube);
    menu->add(cylinder);
    menu->add(sphere);
    menu->add(dzDelete);

    root->setLocation(Point(0,0));
    return root;
}
